project5/app5/urls.py
from django.urls import path
from . import views

app_name = 'app5'
urlpatterns = [
    path('', views.fun1, name='fun1'),
    path('movie/<int:movie_list>/', views.fun2, name='fun2'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

project5/project5/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app5.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project5/app5/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    year = models.IntegerField()
    image = models.ImageField(upload_to='pics')

project5/app5/forms.py
from django import forms
from .models import Movie


class Movie_form(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'image']

project5/app5/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from app5.models import Movie
from .forms import Movie_form


def fun1(request):
    value = Movie.objects.all()
    return render(request, 'index.html', {'key': value})


def fun2(request, movie_list):
    movie = Movie.objects.get(id=movie_list)
    return render(request, 'details.html', {'kiy': movie})


def add_movie(request):
    form = Movie_form(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'add.html', {'form': form})


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = Movie_form(request.POST or None, request.FILES or None, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'update.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

project5/templates/add.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body style="background-color:black">
<div class="row justify-content-center ">
    <div class="col-md-4 ">
<div class="form-control mb-2 bg-dark text-warning border border-warning ">
<form method="POST" enctype="multipart/form-data">

    {%  csrf_token %}
    {{form|crispy}}
    <div class="text-center">
    <button type="submit" class="btn btn-warning ">Submit</button>
    </div>
</form>
</div>
    </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

project5/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body style="background-color:black">
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Movie Store
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project5/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body class="bg-dark">
<div class="container">
<form method="POST" >
    {% csrf_token %}
    <p class="text-center fs-2 text-danger"> do you want to delete this movie</p><br>
    <div class="text-center">
    <button type="submit" class="btn btn-danger ">Delete</button>
    </div>
</form>
</div>

</body>

project5/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
          <img src="{{kiy.image.url}}" width="200" height="200">
             </div>
    <div class="col-md-6 text-warning">
        <h4 >{{kiy.name}}</h4>
        <h6>{{kiy.desc}}</h6>
        <h6>{{kiy.year}}</h6>
           <a class= "btn btn-success" href="{% url 'app5:update' kiy.id %}">update</a>
           <a class= "btn btn-danger" href="{% url 'app5:delete' kiy.id %}">delete</a>
        </div>
    </div>
</div>
{% endblock %}

project5/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class = "container" >
    <div class="row">
        {% for i in key %}
        <div class="col-md-4">
            <div class="card mt-2" style="width: 23rem;height: 27rem ">
            <img class="card-img-top border border-warning" src="{{i.image.url}}" alt="..." width="400" height="200">
               <div class="card-body bg-dark border border-primary">
               <h4 class="card-title text-warning">{{i.name}}</h4>
               <p class="card-text text-warning">{{i.year}}</p>
               <a href="{% url 'app5:fun2' i.id %}" class="btn btn-primary">More info</a>
               </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

project5/templates/update.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body style="background-color:black">
<div class="row justify-content-center ">
    <div class="col-md-4 ">
<div class="form-control mb-2 bg-dark text-success border border-success ">
<form method="POST" enctype="multipart/form-data">

    {%  csrf_token %}
    {{form|crispy}}
    <div class="text-center">
    <button type="submit" class="btn btn-success ">Submit</button>
    </div>
</form>
</div>
    </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>